config/routes.rb
Rails.application.routes.draw do
  get "/:id" => "links#show", :as => "link"
  post "/" => "links#create", :as => "links"
  get "links/new", :as => "new_link"
  root "links#new"
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :original, presence: true

  def to_param
    self.id.to_i.to_s(36)
  end

  def increment
    self.clicks += 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def show
    @link = Link.find(params[:id].to_i(36))
    if redirect_to @link.original
      @link.increment
      @link.save
    end
  end

  def new
    @link = Link.new
    @top_links = Link.order(clicks: :desc).first(100)
  end

  def create
    @link = Link.new(link_params)
      if @link.save!
         render :show, notice: 'Link was successfully created.'
      else
         render :new
      end
  end

  def landing

  end


  private
    def link_params
      params.require(:link).permit(:original, :clicks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CmbillsShortener</title>
  <link href='http://fonts.googleapis.com/css?family=Comfortaa:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
	<% if params["action"]=="create" %>
		<div class="header">
			<%= render "link_header" %>
		</div>
		<div class="content">
			<%= yield %>
		</div>
		<script>
			$(".disappear").hide()
		</script>
	<% else %>
		<div class="header">
			<%= render "header" %>
		</div>
		<div class="content">
			<%= yield %>
		</div>
		<script>	
			$(function(){
				$(".content").hide()
				loadLanding()
			});
		</script>
	<% end %>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link, :html => { :id => "urlForm"}) do |f| %>
  <div class="field">
    <%= f.text_field :original, :class => "required url", :placeholder => "http://www.example.com" %>
  </div>
  <div class="actions">
    <%= f.submit "Shorten!", :class => "shorten" %>
  </div>
<% end %>

app/views/links/_header.html.erb
<div class="testing" >
	<div class="carson">
		<h1> C<span class="disappear">arson</span> </h1>
	</div>

	<div class="bills">
		<h1> B<span class="disappear">ills</span> </h1>
	</div>

	<div class="shortener">
		<h1> URL Shortener <h1>
	</div>
</div>

app/views/links/_link_header.html.erb
<div class="new_link_wrap" >
	<div class="new_link_carson">
		<h1> C<span class="disappear">arson</span> </h1>
	</div>

	<div class="new_link_bills">
		<h1> B<span class="disappear">ills</span> </h1>
	</div>

	<div class="new_link_shortener">
		<h1> URL Shortener <h1>
	</div>
</div>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <thead>
    <tr>
      <th>Original</th>
      <th>Shortened</th>
      <th>Clicks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @top_links.each do |link| %>
      <tr>
        <td><%= link.original%></td>
        <td><%=link_to link_url(link), link_url(link) %> </td>
        <td><%= link.clicks %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<%= render 'form' %>
<div class="top"
  <p> Top Links: </p>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Original</th>
      <th>Shortened</th>
      <th>Clicks</th>
    </tr>
  </thead>

  <tbody>
    <% @top_links.each do |link| %>
      <tr>
        <td><%= link.original%></td>
        <td><%=link_to link_url(link), link_url(link) %> </td>
        <td><%= link.clicks %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>

	$(function(){
		loadTopLinks();
    $(".shorten").hide();
    $("#urlForm").validate({
      errorPlacement: function(error, element) {
        error.insertAfter(".field");
      }
    });
    $(".shorten").fadeIn(200);
	});

</script>

app/views/links/show.html.erb
<div class="short">
	<p id="notice"><%= notice %></p>

	<p class="short_info">The shortened URL is <br> <%= link_to link_url(@link), link_url(@link) %></p>

	<p class="short_info original">
	  <strong>Original:</strong><br>
	  <%= @link.original %>
	</p>

	<p class="short_info">
	  <strong>Clicks:</strong>
	  <%= @link.clicks %>
	</p>
</div>

<div class="back">
	<%= link_to 'Back', links_path %>
</div>